version: "3"
services:
  express:
    container_name: express
    restart: always
    build: ./server
    ports:
      - "8000:8000"
    links:
      - mongo
    depends_on:
      - mongo

  vue:
    container_name: vue
    build: ./client
    ports:
      - "8080:8080"

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongodb-datavolume:/data/db
    ports:
      - "27017:27017"
volumes:
  mongodb-datavolume:
